# @see https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/#how-to-map-an-action-of-your-controller-to-a-uri
ps_demomanufhooksusage_toggle_is_allowed_for_review:
  path: demo-manuf-hook-usage/{manufacturerId}/toggle-is-allowed-for-review
  methods: [POST]
  defaults:
    _controller: 'DemoManufHooksUsage\Controller\Admin\ManufacturerReviewController::toggleIsAllowedForReviewAction'
  requirements:
    manufacturerId: \d+
